spring:
    datasource:
        url: jdbc:mysql://localhost:3306/ctp?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: test
        password: test
    jpa:
        hibernate:
            ddl-auto: update

